# Mobb/semgrep Fixer on pull requests
# This workflow defines the needed steps to run semgrep on every pull request and pass the results to Mobb Fixer.
#
# Secrets in use (add your missing ones):
# MOBB_API_TOKEN - your mobb user credentials (automatically set if you forked this repo via the Mobb app)

name: "Mobb/Semgrep"

on:
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  scan-and-fix:
    name: Scan with Semgrep and fix with Mobb
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      contents: read
      pull-requests: write
      statuses: write
      security-events: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and Run Semgrep CLI
        env:
           SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: |
          pip install semgrep
          semgrep login
          semgrep ci --sarif --output semgrep_report.sarif || true
      
     
      - name: Run Mobb on the findings and get fixes
        if: always()
        uses: mobb-dev/action@added-organization-id
        with:
          report-file: "semgrep_report.sarif"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          mobb-project-name: ${{vars.MOBB_PROJECT_NAME}}
          organization-id: ${{ vars.ORGANIZATION_ID }}
